version: '2'

services:
  zwitscher-consul:
    image: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - zwitscher-net
  zwitscher-traefik:
    image: traefik
    # volumes:
      # - ./traefik.toml:/etc/traefik/traefik.toml
    args:
      - --web
      - --web.address=:8888
      - --consulcatalog
      - --consulcatalog.endpoint=zwitscher-consul:8500
      - --consulcatalog.domain=consul.localhost

    ports:
      - "8888:8888"
      - "80:80"
    depends_on:
      - zwitscher-consul
    links:
      - zwitscher-consul
    networks:
      - zwitscher-net
  zwitscher-service:
    image: wjax2016:1.0.1-${USER}
    environment:
      - CONSUL_HOST=zwitscher-consul
      - CONSUL_PORT=8500
      - TWITTER_APP_ID=${TWITTER_APP_ID}
      - TWITTER_APP_SECRET=${TWITTER_APP_SECRET}
    depends_on:
      - zwitscher-consul
    links:
      - zwitscher-consul
    ports:
      - "8080:8080"
    networks:
      - zwitscher-net

networks:
  zwitscher-net:
